Repository DaangnMarket/DaangnMarket-iOS, pull requests merged in 2023-05, with the labels that each got.

#40 [Design] #20 - 나의당근뷰 프로필 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Global/Extension/UIButton+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UIViewController+.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MyProfileHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SettingViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/[.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/View/ProfileHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/View/ProfileTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/ViewController/ProfileViewController.swift
Labels: 🍋 Soda, Design

#44 [Design] #42 - NoticeView 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Notice/Model/NoticeTableViewModel.swift
  DaangnMarket/DaangnMarket/Presentation/Notice/NoticeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Notice/View/KeywordHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/Notice/View/NoticeTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Notice/ViewController/NoticeViewController.swift
Labels: 🍐 Ollie, Design

#46 [Design] #41 - 나의당근 프로필수정뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Global/Extension/UITextField+.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MyProfileHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/View/ProfileHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/ViewController/ModifyProfileViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/ViewController/ProfileViewController.swift
Labels: 🍋 Soda, Design

#49 [Design]#33 - 프로덕트뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Home/Model/HomeTableViewModel.swift
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Product/Model/OtherProductCollectionViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Product/Model/OtherProductModel.swift
  DaangnMarket/DaangnMarket/Presentation/Product/Model/ProductModel.swift
  DaangnMarket/DaangnMarket/Presentation/Product/View/OtherProductCollectionHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/Product/ViewController/ProductViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Test/TestViewController.swift
Labels: Design

#52 [Design] #28 - SearchView 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DaangnMarket/DaangnMarket/Presentation/Search/Model/RecentSearch.swift
  DaangnMarket/DaangnMarket/Presentation/Search/SearchViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Search/View/RecentSearchesCollectionViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Search/View/RecentSearchesHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/Search/ViewController/SearchViewController.swift
Labels: 🍐 Ollie, Design

#55 [Design]#50 프로덕트뷰 - 화면 및 가격 및 찜하기 레이아웃 구현
  DaangnMarket/DaangnMarket/Presentation/Product/ViewController/ProductViewController.swift
Labels: Feat

#56 [Feat]#37 - 내 동네 설정 뷰 버튼 기능 상세 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/MyAddress/ViewController/MyAddressViewController.swift
  DaangnMarket/DaangnMarket/Presentation/SearchAddress/ViewController/SearchAddressViewController.swift
Labels: Feat

#64 [Feat]/#60 - 내 위치 선택 뷰
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyAddress/ViewController/MyAddressViewController.swift
  DaangnMarket/DaangnMarket/Presentation/SearchAddress/ViewController/SearchAddressViewController.swift
Labels: Feat

#62 [Design] #61 - 관심 목록 뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/WishListViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Profile/ViewController/ModifyProfileViewController.swift
Labels: 🍋 Soda, Design

#66 [Design] #65 - 카카오로그인뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Application/SceneDelegate.swift
  DaangnMarket/DaangnMarket/Presentation/Login/LoginViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/UnderlineSegmentedControl.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/HideViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SellListViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SellingViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SoldViewController.swift
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnMainLogo.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnMainLogo.imageset/DaangnMainLogo.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/KakaoLoginButtonImage.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/KakaoLoginButtonImage.imageset/KakaoLoginButtonImage@1x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/KakaoLoginButtonImage.imageset/KakaoLoginButtonImage@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/KakaoLoginButtonImage.imageset/KakaoLoginButtonImage@3x.png
Labels: 🍋 Soda, Design

#68 [Design] #63 - 판매내역뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Application/SceneDelegate.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SellListViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Test/TestViewController.swift
Labels: 🍋 Soda, Design

#70 Feature/#69 [Design] 채팅뷰 디자인
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Chatting/ChatViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Chatting/Model/ChattingTableViewModel.swift
  DaangnMarket/DaangnMarket/Presentation/Chatting/View/ChattingTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Chatting/ViewController/ChatViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Home/View/HomeTableViewCell.swift
Labels: Design
