Repository DaangnMarket/DaangnMarket-iOS, pull requests merged in 2023-04, with the labels that each got.

#2 [Setting] #1 - 프로젝트 세팅
  .gitignore
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DaangnMarket/DaangnMarket.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DaangnMarket/DaangnMarket/Application/AppDelegate.swift
  DaangnMarket/DaangnMarket/Application/SceneDelegate.swift
  DaangnMarket/DaangnMarket/Global/Extension/UICollectionViewCell+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UIColor+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UIStackView+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UITableViewCell+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UIView+.swift
  DaangnMarket/DaangnMarket/Info.plist
  DaangnMarket/DaangnMarket/Presentation/ViewController.swift
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/Contents.json
  DaangnMarket/DaangnMarket/Resources/Base.lproj/LaunchScreen.storyboard
  DaangnMarket/DaangnMarket/Resources/Base.lproj/Main.storyboard
Labels: 🍋 Soda, Setting

#4 [Setting] #1 - 프로젝트 세팅
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
Labels: 🍋 Soda, Setting

#5 [Feat] #3 - 전체 탭바 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DaangnMarket/DaangnMarket/Application/SceneDelegate.swift
  DaangnMarket/DaangnMarket/Presentation/Chatting/ChatViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Home/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/NearMe/NearMeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/TabBar/TabBarController.swift
  DaangnMarket/DaangnMarket/Presentation/TownLife/TownLifeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/ViewController.swift
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChatting.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChatting.imageset/TabChatting.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChatting.imageset/TabChatting@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChatting.imageset/TabChatting@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChattingSelected.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChattingSelected.imageset/TabChattingSelected.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChattingSelected.imageset/TabChattingSelected@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabChattingSelected.imageset/TabChattingSelected@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHome.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHome.imageset/TabHome.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHome.imageset/TabHome@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHome.imageset/TabHome@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHomeSelected.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHomeSelected.imageset/TabHomeSelected.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHomeSelected.imageset/TabHomeSelected@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabHomeSelected.imageset/TabHomeSelected@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangn.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangn.imageset/TabMyDaangn.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangn.imageset/TabMyDaangn@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangn.imageset/TabMyDaangn@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangnSelected.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangnSelected.imageset/TabMyDaangnSelected.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangnSelected.imageset/TabMyDaangnSelected@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabMyDaangnSelected.imageset/TabMyDaangnSelected@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMe.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMe.imageset/TabNearMe.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMe.imageset/TabNearMe@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMe.imageset/TabNearMe@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMeSelected.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMeSelected.imageset/TabNearMeSelected.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMeSelected.imageset/TabNearMeSelected@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabNearMeSelected.imageset/TabNearMeSelected@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLife.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLife.imageset/TabTownLife.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLife.imageset/TabTownLife@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLife.imageset/TabTownLife@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLifeSelected.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLifeSelected.imageset/TabTownLifeSelected.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLifeSelected.imageset/TabTownLifeSelected@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/TabBar/TabTownLifeSelected.imageset/TabTownLifeSelected@3x.png
Labels: 🍋 Soda, Feat

#7 [Add] #6 - 컬러 추가
  DaangnMarket/DaangnMarket/Global/Extension/UIColor+.swift
Labels: 🍋 Soda, Add

#9 [Feat] #7 - 홈 네비게이션 바 생성
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Home/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Notice/NoticeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Search/SearchViewController.swift
  DaangnMarket/DaangnMarket/Presentation/TabBar/TabBarController.swift
Labels: 🍊Ted, Feat

#11 [Fix] #10 - 탭바 코드 수정
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/TabBar/TabBarController.swift
Labels: 🍋 Soda, Fix

#16 [Feat] #13 - 홈뷰 테이블뷰 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Global/Extension/UIView+.swift
  DaangnMarket/DaangnMarket/Presentation/Home/View/HomeTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🍊Ted, Feat

#17 [Design] #12 - 나의당근뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Global/Extension/UIColor+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UITableViewHeaderFooterView+.swift
  DaangnMarket/DaangnMarket/Global/Extension/UIView+.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/Model/MyDaangnModel.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MyLineFooterView.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MyProfileHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MySectionHeaderView.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/View/MyTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/SettingViewController.swift
  DaangnMarket/DaangnMarket/Presentation/TabBar/TabBarController.swift
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/스크린샷 2023-04-23 오후 9.02.48.png
Labels: 🍋 Soda, Design

#22 [Fix] #21 - 당근페이 로고 이미지 오류 수정
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/Contents.json
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/DaangnPayLogo.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/DaangnPayLogo@2x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/DaangnPayLogo@3x.png
  DaangnMarket/DaangnMarket/Resources/Assets.xcassets/DaangnPayLogo.imageset/스크린샷 2023-04-23 오후 9.02.48.png
Labels: 🍋 Soda, Fix

#25 [Refactor] #23 - 나의당근뷰 navigation bar 코드 수정
  DaangnMarket/DaangnMarket/Presentation/MyDaangn/ViewController/MyDaangnViewController.swift
Labels: 🍋 Soda, Refactor

#27 [Feat] #26 - 동네 설정 네비게이션 바 생성
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Home/Model/HomeCityName.swift
  DaangnMarket/DaangnMarket/Presentation/Home/Model/HomeTableViewModel.swift
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🍊Ted, Feat

#29 [Fix]/#24 - 홈 테이블뷰 데이터 수정
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Home/Model/HomeTableViewModel.swift
  DaangnMarket/DaangnMarket/Presentation/Home/View/HomeTableViewCell.swift
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🍊Ted, Fix

#35 [Fix] #34 - 네비게이션 왼쪽 부분 수정 완료
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/Product/ViewController/ProductViewController.swift
Labels: 🍊Ted, Fix

#39 [ Design] #36 - 내 동네 설정 뷰 레이아웃 구현
  DaangnMarket/DaangnMarket.xcodeproj/project.pbxproj
  DaangnMarket/DaangnMarket/Presentation/Home/ViewController/HomeViewController.swift
  DaangnMarket/DaangnMarket/Presentation/MyAddress/ViewController/MyAddressViewController.swift
Labels: 🍊Ted, Design
